// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Categories string
	Comments   string
	Posts      string
	Users      string
}{
	Categories: "categories",
	Comments:   "comments",
	Posts:      "posts",
	Users:      "users",
}
